Vagrant.configure("2") do |config|
  config.vm.define "k8s-controller" do |subconfig|
    subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "k8s-controller"
#    subconfig.vm.network "public_network"
        subconfig.vm.network "private_network", ip: "192.168.2.100"
#    subconfig.vm.provision "shell", inline:$setup_minikube

        subconfig.vm.provider "virtualbox" do |vb|
                vb.memory = "4096"
                vb.cpus = "2"
        end

  end

  config.vm.define "k8s-worker-1" do |subconfig|
    subconfig.vm.box = "centos/7"
        subconfig.vm.hostname = "k8s-worker-1"
        subconfig.vm.network "private_network", ip: "192.168.2.110"

        subconfig.vm.provider "virtualbox" do |vb|
                vb.memory = "2048"
        end
  end
end
