Vagrant.configure("2") do |config|
  config.vm.define "k8s-cp" do |subconfig|
    subconfig.vm.box = "ubuntu/focal64"
        subconfig.vm.hostname = "k8s-controller"
        subconfig.vm.network "private_network", ip: "192.168.2.100"
        subconfig.vm.provider "virtualbox" do |vb|
                vb.memory = "4096"
                vb.cpus = "2"
        end

  end

  config.vm.define "k8s-w1" do |subconfig|
    subconfig.vm.box = "ubuntu/focal64"
        subconfig.vm.hostname = "k8s-w1"
        subconfig.vm.network "private_network", ip: "192.168.2.110"

        subconfig.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
                vb.cpus = "2"
        end
  end


    config.vm.define "k8s-w2" do |subconfig|
    subconfig.vm.box = "ubuntu/focal64"
        subconfig.vm.hostname = "k8s-w2"
        subconfig.vm.network "private_network", ip: "192.168.2.120"

        subconfig.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
                vb.cpus = "2"
        end
  end

  config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

end
