# k8s minicube Master script

$setup_minikube = <<SCRIPT

# Install epel and utilities

yum install -y epel-release net-tools wget vim conntrack-tools git unzip

# Enable root login in ssh configuration

sed -i "s/^PermitRootLogin no/PermitRootLogin yes/g" /etc/ssh/sshd_config
sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
service sshd restart

# Install docker

useradd docker

yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

yum install -y docker-ce docker-ce-cli containerd.io

usermod -aG docker vagrant

systemctl enable docker
systemctl start docker

#Download and install minikube latest

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm

yum install -y minikube-latest.x86_64.rpm

minikube config set driver docker

#Install kubectl

cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

yum install -y kubectl


SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "k8s-master" do |subconfig|
    subconfig.vm.box = "centos/7"
	subconfig.vm.hostname = "k8s-master"
#    subconfig.vm.network "public_network"
	subconfig.vm.network "private_network", ip: "192.168.2.20"
    subconfig.vm.provision "shell", inline:$setup_minikube
	
	subconfig.vm.provider "virtualbox" do |vb|
		vb.memory = "4096"
		vb.cpus = "4"
	end
    
  end

end

