# -*- mode: ruby -*-
# vi: set ft=ruby :

$setup = <<SCRIPT

# Install epel and utilities

yum install -y epel-release net-tools wget

# Enable root login in ssh configuration

sed -i "s/^PermitRootLogin no/PermitRootLogin yes/g" /etc/ssh/sshd_config
sed -i "s/^PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
service sshd restart

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "devops-client"
  # config.vm.network "private_network", ip: "192.168.2.10"
  config.vm.network "public_network"
  config.vm.provision "shell", inline:$setup 
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  
  config.vm.define "devops-client" do |devops-client|
  end
end
